# Generated by Django 4.2.4 on 2024-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('descripition', models.TextField()),
                ('category', models.CharField(choices=[('FE', 'Fire Extinguishers'), ('FA', 'Fire Alarms system'), ('DR', 'Detector'), ('SN', 'Sprinkler'), ('HY', 'Hydrant'), ('BN', 'Branch-Nozzles'), ('WM', 'Watermist/Cafe System')], max_length=5)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
