# Generated by Django 4.2.4 on 2024-04-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='prodapp',
            field=models.TextField(default=''),
        ),
    ]
